enum WheelSymbol{
Heart,
Club,
Spade,
Diamond,
Cherry,
}

const WheelSymbolSeed: WheelSymbol[] = [
    WheelSymbol.Diamond,
    WheelSymbol.Diamond,
    WheelSymbol.Diamond,
    WheelSymbol.Diamond,
    WheelSymbol.Diamond,
    WheelSymbol.Diamond,
    WheelSymbol.Heart,
    WheelSymbol.Heart,
    WheelSymbol.Heart,
    WheelSymbol.Heart,
    WheelSymbol.Heart,
    WheelSymbol.Heart,
    WheelSymbol.Spade,
    WheelSymbol.Spade,
    WheelSymbol.Spade,
    WheelSymbol.Spade,
    WheelSymbol.Club,
    WheelSymbol.Club,
    WheelSymbol.Club,
    WheelSymbol.Cherry,
]